name: "Test Suite"
on:
  push:
  pull_request:

jobs:
  formatting:
    name: Rustfmt 🖊️
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  clippy:
    name: Rust Clippy 📎
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Clippy Check
        run: cargo clippy -- -D warnings

  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    needs: [formatting, clippy]
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            rust-target: x86_64-unknown-linux-gnu
            executable-name: hydroxide-linux-x86_64
            path: hydroxide
            name: Build Hydroxide Linux x86_64 🐧
          - runner: ubuntu-latest
            rust-target: aarch64-unknown-linux-gnu
            executable-name: hydroxide-linux-aarch64
            path: hydroxide
            name: Build Hydroxide Linux ARM 🐧
          - runner: macos-latest
            rust-target: x86_64-apple-darwin
            executable-name: hydroxide-macos-x86_64
            path: hydroxide
            name: Build Hydroxide MacOS x86_64 🍎
          - runner: macos-latest
            rust-target: aarch64-apple-darwin
            executable-name: hydroxide-macos-aarch64
            path: hydroxide
            name: Build Hydroxide MacOS ARM 🍎
          - runner: windows-latest
            rust-target: x86_64-pc-windows-msvc
            executable-name: hydroxide-windows-x86_64
            path: hydroxide.exe
            name: Build Hydroxide Windows x86_64 🪟
          - runner: windows-latest
            rust-target: aarch64-pc-windows-msvc
            executable-name: hydroxide-windows-aarch64
            path: hydroxide.exe
            name: Build Hydroxide Windows ARM 🪟

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.rust-target }}

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc gcc-aarch64-linux-gnu cmake libssl-dev pkg-config

      - name: Install Dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake openssl

      - name: Install Dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install openssl -y

      - name: Build Project
        run: cargo build --release --target ${{ matrix.rust-target }}

      - name: Run Tests
        if: matrix.rust-target != 'aarch64-pc-windows-msvc'
        run: cargo test --all-features

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.executable-name }}
          path: target/${{ matrix.rust-target }}/release/${{ matrix.path }}
